export const SURAH_AYAH_COUNTS: Record<number, number> = {
  1: 7,
  2: 286,
  3: 200,
  4: 176,
  5: 120,
  6: 165,
  7: 206,
  8: 75,
  9: 129,
  10: 109,
  11: 123,
  12: 111,
  13: 43,
  14: 52,
  15: 99,
  16: 128,
  17: 111,
  18: 110,
  19: 98,
  20: 135,
  21: 112,
  22: 78,
  23: 118,
  24: 64,
  25: 77,
  26: 227,
  27: 93,
  28: 88,
  29: 69,
  30: 60,
  31: 34,
  32: 30,
  33: 73,
  34: 54,
  35: 45,
  36: 83,
  37: 182,
  38: 88,
  39: 75,
  40: 85,
  41: 54,
  42: 53,
  43: 89,
  44: 59,
  45: 37,
  46: 35,
  47: 38,
  48: 29,
  49: 18,
  50: 45,
  51: 60,
  52: 49,
  53: 62,
  54: 55,
  55: 78,
  56: 96,
  57: 29,
  58: 22,
  59: 24,
  60: 13,
  61: 14,
  62: 11,
  63: 11,
  64: 18,
  65: 12,
  66: 12,
  67: 30,
  68: 52,
  69: 52,
  70: 44,
  71: 28,
  72: 28,
  73: 20,
  74: 56,
  75: 40,
  76: 31,
  77: 50,
  78: 40,
  79: 46,
  80: 42,
  81: 29,
  82: 19,
  83: 36,
  84: 25,
  85: 22,
  86: 17,
  87: 19,
  88: 26,
  89: 30,
  90: 20,
  91: 15,
  92: 21,
  93: 11,
  94: 8,
  95: 8,
  96: 19,
  97: 5,
  98: 8,
  99: 8,
  100: 11,
  101: 11,
  102: 8,
  103: 3,
  104: 9,
  105: 5,
  106: 4,
  107: 7,
  108: 3,
  109: 6,
  110: 3,
  111: 5,
  112: 4,
  113: 5,
  114: 6
};

export const TOTAL_AYAHS = 6236;

export function getTotalMemorizedAyahs(ayahProgress: Array<{memorization_complete: boolean}>): number {
  return ayahProgress.filter(a => a.memorization_complete).length;
}

export function calculateOverallProgress(memorizedCount: number): number {
  return Math.round((memorizedCount / TOTAL_AYAHS) * 100);
}

export interface SurahInfo {
  number: number;
  name: string;
  englishName: string;
  ayahCount: number;
  theme: string;
}

export const SURAHS_DATA: SurahInfo[] = [
  { number: 1, name: 'Al-Fatihah', englishName: 'The Opening', ayahCount: 7, theme: 'The Opening chapter serves as a comprehensive prayer and the foundation of Islamic worship, emphasizing praise of Allah, seeking guidance, and the path of righteousness.' },
  { number: 2, name: 'Al-Baqarah', englishName: 'The Cow', ayahCount: 286, theme: 'The longest chapter covering comprehensive Islamic teachings including faith, law, history of previous prophets, and guidance for Muslim community life.' },
  { number: 3, name: 'Ali \'Imran', englishName: 'Family of Imran', ayahCount: 200, theme: 'Focuses on the stories of prophets, particularly Jesus and his mother Mary, emphasizing monotheism and steadfastness in faith.' },
  { number: 4, name: 'An-Nisa', englishName: 'The Women', ayahCount: 176, theme: 'Addresses social legislation, particularly regarding women\'s rights, inheritance, marriage, and family law in Islam.' },
  { number: 5, name: 'Al-Ma\'idah', englishName: 'The Table', ayahCount: 120, theme: 'Discusses dietary laws, covenants with Allah, and the relationship between Muslims and People of the Book.' },
  { number: 6, name: 'Al-An\'am', englishName: 'The Cattle', ayahCount: 165, theme: 'Emphasizes Allah\'s oneness, creation, and refutation of polytheism through logical arguments.' },
  { number: 7, name: 'Al-A\'raf', englishName: 'The Heights', ayahCount: 206, theme: 'Recounts stories of various prophets and their struggles against disbelief, warning against rejecting divine guidance.' },
  { number: 8, name: 'Al-Anfal', englishName: 'The Spoils of War', ayahCount: 75, theme: 'Provides guidance on conduct during war, distribution of war gains, and lessons from the Battle of Badr.' },
  { number: 9, name: 'At-Tawbah', englishName: 'The Repentance', ayahCount: 129, theme: 'Addresses relations with non-believers, hypocrites, and the importance of sincere repentance and charity.' },
  { number: 10, name: 'Yunus', englishName: 'Jonah', ayahCount: 109, theme: 'Story of Prophet Jonah emphasizing Allah\'s mercy, the reality of revelation, and consequences of rejecting prophets.' },
  { number: 11, name: 'Hud', englishName: 'Hud', ayahCount: 123, theme: 'Chronicles several prophets\' experiences with their communities and the fate of those who reject guidance.' },
  { number: 12, name: 'Yusuf', englishName: 'Joseph', ayahCount: 111, theme: 'The complete story of Prophet Joseph, demonstrating patience, trust in Allah, and ultimate triumph over adversity.' },
  { number: 13, name: 'Ar-Ra\'d', englishName: 'The Thunder', ayahCount: 43, theme: 'Emphasizes Allah\'s power over creation, signs of His existence, and the truth of the Quran.' },
  { number: 14, name: 'Ibrahim', englishName: 'Abraham', ayahCount: 52, theme: 'Highlights Prophet Abraham\'s prayer and steadfast faith, contrasting guidance with misguidance.' },
  { number: 15, name: 'Al-Hijr', englishName: 'The Rocky Tract', ayahCount: 99, theme: 'Warns against rejecting prophets through historical examples and emphasizes protection of the Quran.' },
  { number: 16, name: 'An-Nahl', englishName: 'The Bee', ayahCount: 128, theme: 'Points to Allah\'s countless blessings in nature and emphasizes gratitude and recognition of divine favors.' },
  { number: 17, name: 'Al-Isra', englishName: 'The Night Journey', ayahCount: 111, theme: 'Recounts the Prophet\'s miraculous night journey and provides comprehensive moral and ethical teachings.' },
  { number: 18, name: 'Al-Kahf', englishName: 'The Cave', ayahCount: 110, theme: 'Contains stories testing faith including the People of the Cave, Moses and Khidr, and Dhul-Qarnayn.' },
  { number: 19, name: 'Maryam', englishName: 'Mary', ayahCount: 98, theme: 'Honors Mary, mother of Jesus, and discusses prophetic lineage emphasizing Allah\'s mercy and power.' },
  { number: 20, name: 'Ta-Ha', englishName: 'Ta-Ha', ayahCount: 135, theme: 'Story of Moses\' prophethood, his mission to Pharaoh, and guidance for dealing with adversity.' },
  { number: 21, name: 'Al-Anbiya', englishName: 'The Prophets', ayahCount: 112, theme: 'Recounts stories of various prophets as examples of faith and perseverance in the face of adversity.' },
  { number: 22, name: 'Al-Hajj', englishName: 'The Pilgrimage', ayahCount: 78, theme: 'Discusses the significance of Hajj and emphasizes monotheism and rejection of false deities.' },
  { number: 23, name: 'Al-Mu\'minun', englishName: 'The Believers', ayahCount: 118, theme: 'Describes the characteristics of true believers and their ultimate success in the Hereafter.' },
  { number: 24, name: 'An-Nur', englishName: 'The Light', ayahCount: 64, theme: 'Provides social and moral guidance, including rules on modesty, slander, and family ethics.' },
  { number: 25, name: 'Al-Furqan', englishName: 'The Criterion', ayahCount: 77, theme: 'Discusses the Quran as the criterion between truth and falsehood and attributes of the righteous.' },
  { number: 26, name: 'Ash-Shu\'ara', englishName: 'The Poets', ayahCount: 227, theme: 'Narrates stories of various prophets and their rejection by their communities.' },
  { number: 27, name: 'An-Naml', englishName: 'The Ant', ayahCount: 93, theme: 'Features stories of Solomon and other prophets, emphasizing wisdom and divine knowledge.' },
  { number: 28, name: 'Al-Qasas', englishName: 'The Stories', ayahCount: 88, theme: 'Details the story of Moses from birth to prophethood, demonstrating Allah\'s plan and protection.' },
  { number: 29, name: 'Al-\'Ankabut', englishName: 'The Spider', ayahCount: 69, theme: 'Emphasizes that faith is tested and uses the spider\'s web as a metaphor for false security.' },
  { number: 30, name: 'Ar-Rum', englishName: 'The Romans', ayahCount: 60, theme: 'Discusses signs of Allah in creation and the rise and fall of civilizations.' },
  { number: 31, name: 'Luqman', englishName: 'Luqman', ayahCount: 34, theme: 'Contains the wise advice of Luqman to his son about faith, gratitude, and proper conduct.' },
  { number: 32, name: 'As-Sajdah', englishName: 'The Prostration', ayahCount: 30, theme: 'Emphasizes the reality of revelation, resurrection, and the contrast between believers and disbelievers.' },
  { number: 33, name: 'Al-Ahzab', englishName: 'The Combined Forces', ayahCount: 73, theme: 'Discusses the Battle of the Trench and establishes various social and family laws.' },
  { number: 34, name: 'Saba', englishName: 'Sheba', ayahCount: 54, theme: 'Recounts the story of the people of Sheba and emphasizes gratitude for Allah\'s blessings.' },
  { number: 35, name: 'Fatir', englishName: 'The Originator', ayahCount: 45, theme: 'Affirms Allah as the Creator and highlights the contrast between belief and disbelief.' },
  { number: 36, name: 'Ya-Sin', englishName: 'Ya-Sin', ayahCount: 83, theme: 'Known as the heart of the Quran, emphasizes resurrection and the certainty of divine revelation.' },
  { number: 37, name: 'As-Saffat', englishName: 'Those Ranged in Ranks', ayahCount: 182, theme: 'Describes angels in ranks, stories of prophets, and the reality of the Hereafter.' },
  { number: 38, name: 'Sad', englishName: 'Sad', ayahCount: 88, theme: 'Focuses on Prophet David and Solomon, emphasizing patience and proper judgment.' },
  { number: 39, name: 'Az-Zumar', englishName: 'The Groups', ayahCount: 75, theme: 'Discusses sincere worship of Allah alone and the ultimate grouping of people on Judgment Day.' },
  { number: 40, name: 'Ghafir', englishName: 'The Forgiver', ayahCount: 85, theme: 'Emphasizes Allah\'s forgiveness and power, and the fate of those who reject faith.' },
  { number: 41, name: 'Fussilat', englishName: 'Explained in Detail', ayahCount: 54, theme: 'Describes the Quran as a detailed explanation and warns against arrogance and disbelief.' },
  { number: 42, name: 'Ash-Shuraa', englishName: 'The Consultation', ayahCount: 53, theme: 'Emphasizes consultation in community affairs and describes divine revelation.' },
  { number: 43, name: 'Az-Zukhruf', englishName: 'The Gold Adornments', ayahCount: 89, theme: 'Discusses materialism and the temporary nature of worldly attractions.' },
  { number: 44, name: 'Ad-Dukhan', englishName: 'The Smoke', ayahCount: 59, theme: 'Warns of the Day of Judgment using the metaphor of smoke and recounts Pharaoh\'s story.' },
  { number: 45, name: 'Al-Jathiyah', englishName: 'The Kneeling', ayahCount: 37, theme: 'Describes how all creation will kneel before Allah on the Day of Judgment.' },
  { number: 46, name: 'Al-Ahqaf', englishName: 'The Wind-Curved Sandhills', ayahCount: 35, theme: 'Narrates the destruction of \'Ad and emphasizes patience in conveying truth.' },
  { number: 47, name: 'Muhammad', englishName: 'Muhammad', ayahCount: 38, theme: 'Discusses fighting in the cause of Allah and describes believers and hypocrites.' },
  { number: 48, name: 'Al-Fath', englishName: 'The Victory', ayahCount: 29, theme: 'Commemorates the Treaty of Hudaybiyyah as a clear victory for Islam.' },
  { number: 49, name: 'Al-Hujurat', englishName: 'The Rooms', ayahCount: 18, theme: 'Provides guidance on proper manners and ethics within the Muslim community.' },
  { number: 50, name: 'Qaf', englishName: 'Qaf', ayahCount: 45, theme: 'Emphasizes the reality of resurrection and describes the creation as proof of Allah\'s power.' },
  { number: 51, name: 'Adh-Dhariyat', englishName: 'The Winnowing Winds', ayahCount: 60, theme: 'Takes oaths by natural phenomena to affirm the truth of resurrection and judgment.' },
  { number: 52, name: 'At-Tur', englishName: 'The Mount', ayahCount: 49, theme: 'Takes an oath by Mount Sinai and describes the reality of divine punishment.' },
  { number: 53, name: 'An-Najm', englishName: 'The Star', ayahCount: 62, theme: 'Affirms the Prophet\'s experience of divine revelation and refutes idol worship.' },
  { number: 54, name: 'Al-Qamar', englishName: 'The Moon', ayahCount: 55, theme: 'Recounts stories of destroyed nations as warnings, with the splitting of the moon as a sign.' },
  { number: 55, name: 'Ar-Rahman', englishName: 'The Most Merciful', ayahCount: 78, theme: 'Lists the countless blessings of Allah, repeatedly asking "Which favors will you deny?"' },
  { number: 56, name: 'Al-Waqi\'ah', englishName: 'The Inevitable', ayahCount: 96, theme: 'Describes the three groups of people on the Day of Judgment and their respective fates.' },
  { number: 57, name: 'Al-Hadid', englishName: 'The Iron', ayahCount: 29, theme: 'Discusses the nature of worldly life, encourages charity, and mentions iron as a divine gift.' },
  { number: 58, name: 'Al-Mujadila', englishName: 'The Pleading Woman', ayahCount: 22, theme: 'Addresses the case of a woman pleading about her husband and discusses hypocrites.' },
  { number: 59, name: 'Al-Hashr', englishName: 'The Exile', ayahCount: 24, theme: 'Discusses the exile of Jewish tribes and emphasizes contemplation of the Quran.' },
  { number: 60, name: 'Al-Mumtahanah', englishName: 'The Examined One', ayahCount: 13, theme: 'Provides guidance on dealing with non-Muslims and testing the faith of immigrant women.' },
  { number: 61, name: 'As-Saff', englishName: 'The Ranks', ayahCount: 14, theme: 'Encourages believers to stand firm in ranks and discusses Prophet Jesus foretelling Muhammad.' },
  { number: 62, name: 'Al-Jumu\'ah', englishName: 'The Friday', ayahCount: 11, theme: 'Emphasizes the importance of Friday prayer and balance between worship and livelihood.' },
  { number: 63, name: 'Al-Munafiqun', englishName: 'The Hypocrites', ayahCount: 11, theme: 'Exposes the characteristics and dangers of hypocrites within the Muslim community.' },
  { number: 64, name: 'At-Taghabun', englishName: 'The Mutual Loss and Gain', ayahCount: 18, theme: 'Discusses the Day of Judgment as a day of mutual loss and gain between people.' },
  { number: 65, name: 'At-Talaq', englishName: 'The Divorce', ayahCount: 12, theme: 'Provides detailed laws regarding divorce, waiting periods, and fair treatment.' },
  { number: 66, name: 'At-Tahrim', englishName: 'The Prohibition', ayahCount: 12, theme: 'Addresses domestic matters in the Prophet\'s household and provides examples of believers.' },
  { number: 67, name: 'Al-Mulk', englishName: 'The Sovereignty', ayahCount: 30, theme: 'Affirms Allah\'s sovereignty over all creation and discusses life, death, and accountability.' },
  { number: 68, name: 'Al-Qalam', englishName: 'The Pen', ayahCount: 52, theme: 'Defends the Prophet against accusations and discusses the importance of good character.' },
  { number: 69, name: 'Al-Haqqah', englishName: 'The Inevitable Reality', ayahCount: 52, theme: 'Describes the Day of Judgment and its inevitable reality that cannot be denied.' },
  { number: 70, name: 'Al-Ma\'arij', englishName: 'The Ways of Ascent', ayahCount: 44, theme: 'Describes the ascent to Allah and characteristics that lead to success in the Hereafter.' },
  { number: 71, name: 'Nuh', englishName: 'Noah', ayahCount: 28, theme: 'Recounts Prophet Noah\'s patient call to his people over 950 years and their rejection.' },
  { number: 72, name: 'Al-Jinn', englishName: 'The Jinn', ayahCount: 28, theme: 'Describes how jinn responded to hearing the Quran and their acknowledgment of its truth.' },
  { number: 73, name: 'Al-Muzzammil', englishName: 'The Enshrouded One', ayahCount: 20, theme: 'Encourages night prayer and patience in conveying the message despite opposition.' },
  { number: 74, name: 'Al-Muddaththir', englishName: 'The Cloaked One', ayahCount: 56, theme: 'Commands the Prophet to warn people and describes consequences of rejection.' },
  { number: 75, name: 'Al-Qiyamah', englishName: 'The Resurrection', ayahCount: 40, theme: 'Affirms the reality of resurrection and describes human accountability for actions.' },
  { number: 76, name: 'Al-Insan', englishName: 'The Human', ayahCount: 31, theme: 'Describes human creation and the rewards awaiting righteous believers in Paradise.' },
  { number: 77, name: 'Al-Mursalat', englishName: 'Those Sent Forth', ayahCount: 50, theme: 'Takes oaths by natural phenomena to emphasize the certainty of the Day of Judgment.' },
  { number: 78, name: 'An-Naba', englishName: 'The Tidings', ayahCount: 40, theme: 'Announces the great news of resurrection and describes Paradise and Hell.' },
  { number: 79, name: 'An-Nazi\'at', englishName: 'Those Who Pull Out', ayahCount: 46, theme: 'Takes oaths by angels and describes the overwhelming event of resurrection.' },
  { number: 80, name: '\'Abasa', englishName: 'He Frowned', ayahCount: 42, theme: 'Reminds the Prophet to give equal attention to all seekers of knowledge, regardless of status.' },
  { number: 81, name: 'At-Takwir', englishName: 'The Overthrowing', ayahCount: 29, theme: 'Describes cosmic events of the Day of Judgment and affirms the Quran\'s divine origin.' },
  { number: 82, name: 'Al-Infitar', englishName: 'The Cleaving', ayahCount: 19, theme: 'Describes the splitting of the sky on Judgment Day and angels recording deeds.' },
  { number: 83, name: 'Al-Mutaffifin', englishName: 'The Defrauders', ayahCount: 36, theme: 'Warns against cheating in business and describes the records of the righteous and wicked.' },
  { number: 84, name: 'Al-Inshiqaq', englishName: 'The Splitting Open', ayahCount: 25, theme: 'Describes the sky splitting open and humans meeting their Lord with their record of deeds.' },
  { number: 85, name: 'Al-Buruj', englishName: 'The Constellations', ayahCount: 22, theme: 'Tells of the people of the ditch who persecuted believers and emphasizes Allah\'s power.' },
  { number: 86, name: 'At-Tariq', englishName: 'The Night-Comer', ayahCount: 17, theme: 'Takes an oath by the piercing star and affirms resurrection and divine protection.' },
  { number: 87, name: 'Al-A\'la', englishName: 'The Most High', ayahCount: 19, theme: 'Glorifies Allah\'s name and discusses ease in remembrance and ultimate success.' },
  { number: 88, name: 'Al-Ghashiyah', englishName: 'The Overwhelming', ayahCount: 26, theme: 'Describes the overwhelming event of Judgment Day and the contrasting fates of people.' },
  { number: 89, name: 'Al-Fajr', englishName: 'The Dawn', ayahCount: 30, theme: 'Takes oaths by dawn and night, warning against love of wealth and neglect of the needy.' },
  { number: 90, name: 'Al-Balad', englishName: 'The City', ayahCount: 20, theme: 'Takes an oath by Makkah and discusses the steep path of righteousness and helping others.' },
  { number: 91, name: 'Ash-Shams', englishName: 'The Sun', ayahCount: 15, theme: 'Takes oaths by cosmic phenomena and discusses purification of the soul versus corruption.' },
  { number: 92, name: 'Al-Layl', englishName: 'The Night', ayahCount: 21, theme: 'Contrasts the night and day, and the paths of the generous believer versus the miser.' },
  { number: 93, name: 'Ad-Duhaa', englishName: 'The Morning Light', ayahCount: 11, theme: 'Consoles the Prophet and reminds him of Allah\'s past favors and future rewards.' },
  { number: 94, name: 'Ash-Sharh', englishName: 'The Relief', ayahCount: 8, theme: 'Assures the Prophet that with hardship comes ease and encourages devotion to Allah.' },
  { number: 95, name: 'At-Tin', englishName: 'The Fig', ayahCount: 8, theme: 'Takes oaths by sacred places and discusses human creation in the best form.' },
  { number: 96, name: 'Al-\'Alaq', englishName: 'The Clot', ayahCount: 19, theme: 'The first revelation, commanding to read in Allah\'s name and affirming divine knowledge.' },
  { number: 97, name: 'Al-Qadr', englishName: 'The Night of Decree', ayahCount: 5, theme: 'Describes the Night of Decree when the Quran was first revealed, better than a thousand months.' },
  { number: 98, name: 'Al-Bayyinah', englishName: 'The Clear Evidence', ayahCount: 8, theme: 'Discusses the clear evidence brought by the Prophet and sincere worship of Allah alone.' },
  { number: 99, name: 'Az-Zalzalah', englishName: 'The Earthquake', ayahCount: 8, theme: 'Describes the great earthquake of Judgment Day when all deeds will be revealed and judged.' },
  { number: 100, name: 'Al-\'Adiyat', englishName: 'The Courser', ayahCount: 11, theme: 'Takes oaths by war horses to illustrate human ingratitude despite Allah\'s knowledge of all.' },
  { number: 101, name: 'Al-Qari\'ah', englishName: 'The Striking Hour', ayahCount: 11, theme: 'Describes the striking hour of Judgment when people\'s deeds will be weighed.' },
  { number: 102, name: 'At-Takathur', englishName: 'The Rivalry', ayahCount: 8, theme: 'Warns against distraction by material rivalry until one visits the graves.' },
  { number: 103, name: 'Al-\'Asr', englishName: 'The Time', ayahCount: 3, theme: 'States that humans are in loss except those with faith, good deeds, truth, and patience.' },
  { number: 104, name: 'Al-Humazah', englishName: 'The Slanderer', ayahCount: 9, theme: 'Warns those who slander and hoard wealth of severe punishment in the Hereafter.' },
  { number: 105, name: 'Al-Fil', englishName: 'The Elephant', ayahCount: 5, theme: 'Recounts how Allah protected the Kaaba from Abraha\'s army with the elephant.' },
  { number: 106, name: 'Quraysh', englishName: 'Quraysh', ayahCount: 4, theme: 'Reminds the Quraysh tribe to worship Allah who provided them security and sustenance.' },
  { number: 107, name: 'Al-Ma\'un', englishName: 'The Small Kindnesses', ayahCount: 7, theme: 'Denounces those who deny religion by neglecting orphans and prayer.' },
  { number: 108, name: 'Al-Kawthar', englishName: 'The Abundance', ayahCount: 3, theme: 'Promises the Prophet abundant good and declares his enemies will be cut off.' },
  { number: 109, name: 'Al-Kafirun', englishName: 'The Disbelievers', ayahCount: 6, theme: 'Clearly distinguishes between the worship of believers and disbelievers.' },
  { number: 110, name: 'An-Nasr', englishName: 'The Help', ayahCount: 3, theme: 'Foretells the conquest of Makkah and commands glorification and seeking forgiveness.' },
  { number: 111, name: 'Al-Masad', englishName: 'The Palm Fiber', ayahCount: 5, theme: 'Condemns Abu Lahab and his wife for their opposition to Islam and the Prophet.' },
  { number: 112, name: 'Al-Ikhlas', englishName: 'The Sincerity', ayahCount: 4, theme: 'Declares the pure monotheistic nature of Allah in the clearest terms.' },
  { number: 113, name: 'Al-Falaq', englishName: 'The Daybreak', ayahCount: 5, theme: 'Seeks refuge in Allah from the evil of creation, darkness, and envy.' },
  { number: 114, name: 'An-Nas', englishName: 'Mankind', ayahCount: 6, theme: 'Seeks refuge in Allah from the evil whispers of Satan affecting human hearts.' }
];
